# Build settings
markdown: redcarpet
highlighter: pygments
gems:
  - jemoji
  
# Site settings
title: "Happy Apprentice"
description: > # this means to ignore newlines until "email:"
   Learn the Rules like a Pro, so Can Break Them like an Artist

email: tonysun329@gmail.com
#blog logo
logo: "/assets/images/selfie_logo.jpg"
# blog cover
cover: "/assets/images/roads/make-your-own-path.JPG"

name: 'Kai Sun'
author: 'Kai Sun'
author_image: "/assets/images/selfie_logo.jpg"

paginate:	5

url: "http://localhost:4000" # the base hostname & protocol for your site
baseurl: ""

# social icons and sharing options
social:
  # - icon:	twitter
  #   url:	https://twitter.com/dirkfabisch
  #   desc: Follow me on twitter
  #   share_url: http://twitter.com/share
  #   share_title: ?text=
  #   share_link: "&amp;url="

  - icon:	facebook
    url:	https://www.facebook.com/tonysun329
    desc: Connect with me facebook
    share_url: https://www.facebook.com/sharer.php
    share_title: ?t=
    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/sunkai612/
    desc:	Check me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
